### ISSUE TITLE
Consider extending the LogEntry template to have a Message field

### ISSUE THREAD

**Issue by geeknoid** [istio/mixer#1110]
Right now, the LogEntry template looks like:

```proto
message Template {
    // Variables that are delivered for each log entry.
    map<string, istio.mixer.v1.config.descriptor.ValueType> variables = 1;

    // Timestamp is the time value for the log entry
//    google.protobuf.Timestamp timestamp = 2;

    // Severity indicates the importance of the log entry.
    string severity = 3;
}
```

I think it would be a good thing to add a Message field in here which would be filled in by the operator when defining instances. The variables generally come from the attributes, the message comes from the operator.

```yaml
  kind: Instance
  apiVersion: config.istio.io/v1beta1
  metadata:
    name: myInstance
  spec:
    template: istio.mixer.template.LogEntry
    params:
      message: "I've got something to say"
      variables:
        source: origin.service
        targetIp: destination.ip
```

@ZackButcher @douglas-reid WDYT?
