### ISSUE TITLE
Create mixer command to generate CRD definitions

### ISSUE THREAD

**Issue by mandarjog** [istio/mixer#1112]
`map[string]*adapter.BuilderInfo` and  `templateInfo map[string]template.Info` should be used to create CRD definitions.

pr #1111 initializes `adapter.BuilderInfo` with a dns1023 compatible shortName.

For example this is how denier CRD should look like where
```
Name: istio.io/mixer/adapter/denier               
ShortName: denier-mixer-istio-io
```

```
kind: CustomResourceDefinition
metadata:
 name: ${shortname}.config.istio.io
 labels:
    impl: ${Name} 
    istio: mixer-adapter
spec:
 group: config.istio.io
 version: v1alpha2
 scope: Namespaced
 names:
   plural: ${shortname}s
   singular: ${shortname}
   kind: ${shortname}
```

in case of mesh functions (instances) it is adapter.Info.Name and impl is HndlrInterfaceName.
istio label is set to mixer-instance.

```
Name:               "istio.mixer.adapter.sample.check"
```
```
kind: CustomResourceDefinition
metadata:
 name: ${Name}.config.istio.io
 labels:
    impl: ${HndlrInterfaceName} 
    istio: mixer-instance
spec:
 group: config.istio.io
 version: v1alpha2
 scope: Namespaced
 names:
   plural: ${Name}s
   singular: ${Name}
   kind: ${Name}
```
