### ISSUE TITLE
Config should support implied "current" namespace for mixer-rules

### ISSUE THREAD

**Issue by mandarjog** [istio/mixer#1184]
Mixer rules require that handler and instances names be fully qualified.
It is make configurations tedious and non portable. If namespace is omitted, the name space of the document should be used.

Current version
```
apiVersion: "config.istio.io/v1alpha2"
kind: memquota
metadata:
  name: memquota
  namespace: istio-config-default
spec:
  quotas:
  - name: requestcount1
    max_amount: 5
    valid_duration: 1s
---
apiVersion: "config.istio.io/v1alpha2"
kind: quota
metadata:
  name: requestcount1
  namespace: istio-config-default
spec:
  dimensions:
    source: source.labels["app"] | "unknown"
    target: target.service | "unknown"
---
apiVersion: "config.istio.io/v1alpha2"
kind: mixer-rule
metadata:
  name: quota
  namespace: istio-config-default
spec:
  selector: "true"
  actions:
  - handler: memquota.memquota.istio-config-default
    instances:
    - requestcount1.quota.istio-config-default
---
```
New version
```
---
apiVersion: "config.istio.io/v1alpha2"
kind: mixer-rule
metadata:
  name: quota
  namespace: istio-config-default
spec:
  selector: "true"
  actions:
  - handler: memquota.memquota
    instances:
    - requestcount1.quota
---
```
