### ISSUE TITLE
Rename `Rule` to `ActionRule` for consistency.

### ISSUE THREAD

**Issue by mandarjog** [istio/mixer#1439]
>>>
Frank Budinsky: Although "rule" is short and sweet, this is a terrible name within the context of the whole of Istio. For consistency with `RouteRule` (the rule for activating a route) I would suggest `ActionRule` (the rule for calling an action)
>>>

This is a breaking change, We will first add an alias, and then remove `rule`.
Gives us a way to practice deprecation :-) 

cc: @frankbu

**Comment by linsun** [comment]
> Gives us a way to practice deprecation :-)

haha I love your optimistic :)

**Comment by rshriram** [comment]
which rule is this? how about PolicyRule and TelemetryRule ?

**Comment by frankbu** [comment]
This is the rule for calling mixer - for policy and telemetry. I suggested `ActionRule` because in mixer terminology, `Actions` are used to make calls to mixer, e.g.:
```
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: promcount
  namespace: istio-system
spec:
- match: destination.service == "*"
  actions:
  - handler: handler.prometheus
    instances:
    - RequestCount.metric
```
The `match` and `actions` fields of an `ActionRule` are very consistent with `RouteRule`'s `match` and `route` fields.
