### ISSUE TITLE
Need generic env attribute generation adapter

### ISSUE THREAD

**Issue by douglas-reid** [istio/mixer#1448]
cc @andraxylia @ldemailly @mandarjog @guptasu 

In testing VM TCP scenarios, it became obvious that Mixer's `kubernetes` adapter was insufficient for handling attribute generation for services running outside of a kubernetes cluster. There are a number of potential solutions, including making the `kubernetes` adapter more robust (add Endpoints / Services cache).

However, there is probably a need for a more simple, easy to configure adapter that can take a `uid` for a workload and generate values from handler configuration, without outside lookups. This adapter should be straightforward to add once the work on porting APAs over to the improved adapter model is complete.

Possible config story:

```yaml
apiVersion: "config.istio.io/v1alpha2"
kind: attributegen
metadata:
  name: handler
  namespace: istio-system
spec:
  workloads:
  - uid: "vm://mysqldb.local"
    outputs:
      service: "mysqldb.default.svc.cluster.local"
      name: "mysqldb"
      labels:
        version: "v2"
        app: "mysqldb"        
```
