### ISSUE TITLE
Delineate config and request state by adding Request Args

### ISSUE THREAD

**Issue by mandarjog** [istio/mixer#201]
It results in a more understandable configuration that can be validated early.

It creates a clean separation between constructor configuration and request state.

Based on 
https://docs.google.com/document/d/1PkGbjYeiNzcx8l43E0diXoXKhXHHRo8_QA1_ghyFdMk/edit#heading=h.s01ziym7eywb

We need to have different messages to represent config parameters vs. request parameters. The current listChecker configuration would go from:

```proto
message ListCheckerParams {
  bool blacklist = 1;
  string check_attribute = 2;
}

to:

// configuration, consistent for a deployment
message ListCheckerConfig {
  bool blacklist = 1;
}

// per-request state, changes for each request flowing through the mixer
message ListCheckerRequestArgs {
  string symbol = 2;
}
```

Following is an example of how one would do this metric and quota descriptors.

```yml
 - kind: ratelimiter
    params:
      limits:  # imposes 2 limits, 100/s per source and destination
      - limit: "100/s"
        labels:
          - label: src.user_id
          - label: target.service_id
       - limit: "1000/s"  # every destination service gets 1000/s
        labels:
          - label: target.service_id

metric_descriptor:
 name: "test_metric"
 type: DELTA / INT64
 label: "user_name", string
 label: "url", Url   

-----
- kind: metric
  params:
      ["test_metric", "test_metric1"]
  requestArgs:
   metric:    --> map[string]string
     - value: $request_count
       descriptor: "test_metric"
       user_name: ($foo | $bar)
       url: ($fooUrl | $barUrl) 
```
      
```python    
 AspectManager.Execute(cfg, bag):
         me := MetricEntry()
         for ra in cfg.RequestArgs:
                 md = lookupMetricDesc(ra.descriptor)
                 me.user_name = evalString(ra.user_name, bag)
                 me.url = (md[user_name].type) evalUrl(ra.url, bag)

          w.asp.send(me)
```

**Comment by mandarjog** [comment]
@geeknoid In the `iplistchecker` the `configArgs` and `requestArgs` are orthogonal.
We could therefore define requestArgs as a typed message.
requestArgs is indeed what is being passed down to the aspect.

In the metrics above, it appears that the shape of `requestArgs` falls out of the metric descriptor. Which means requestArgs cannot be more prescriptive than a `list of maps[string]string`

The keys of the `RequestArgs` map depend on the specific values of the metric descriptor.
A `RequestArgs` of `list of maps` can be processed by us easily; however providing `user`  guidance on which keys to include is challenging.

**Comment by geeknoid** [comment]
Within the code, the RequestArgs for metrics should be defined in terms of a map[string]interface{}, not a map[string]string. These are all strongly-typed values.

The use of descriptors is effectively introducing a new data type through config. We lack this type within the adapter proper, so the example Execute method isn't possible to write. That is, the fields user_name and url don't exist in the code.

For the operator, the pattern is fairly simple. The operator defines the descriptor and is then expected to create instances of that descriptor. This is just like defining a struct type in Go and creating variables of that type. The key lies in making this obvious and discoverable. I think terminology and data layout matter quite a bit here. There are many options we can play with. For example, consider this variation:

```
metric_descriptor:
  name: "test_metric"
  value: DELTA / INT64
  labels:
    user_name: string
    url: Url   

metric:
  descriptor: "test_metric"
  value: $request_count
  labels:
    user_name: ($foo | $bar)
    url: ($fooUrl | $barUrl) 

```

This is not proper YAML, but I think you get the idea. The operator defines a type, and then creates instances of that type. We make the definition and use have the same shape so there's an easy mental mapping between the two. The RequestArgs corresponding to the above would be something like:

```
type RequestArgs struct {
  Descriptor string
  Value interface{}    // type determined by descriptor
  Labels map[string]interface{}   // types again determined by descriptor
}

```
