### ISSUE TITLE
Adapter Model: cached adapter.NewAspect()

### ISSUE THREAD

**Issue by mandarjog** [istio/mixer#337]
Update adapter model so that results of adapter.NewAspect() can be independently cached by Mixer.
This ensures that every AspectWrapper does not open a new connection to the backend when they share the same `AdapterConfig`.

Investigate how
1. Mixer can directly call adapter.NewAspect() 
2. AspectManager.Execute will get a reference to the object created in (1), which should be used as a pooled connection. 

This will involve several internal API changes.

Details:
In mixer we have `Adapters` 
```
  - name: default
    kind: metrics
    impl: statsd
    params:
        host: statsd.svc.cluster.local
```
And `Aspects`
```
  - kind: metrics
    params:
      metrics:
      - descriptor_name: request_count
        value: "1"
        labels:
          source: source.name | "unknown"
          target: target.name | "unknown"
          service: api.name | "unknown"
          method: api.method | "unknown"
          response_code: response.http.code | 200
```

At present `NewAspect  --> aspect.Wrapper`, this aspect Wrapper contains the  object produced by the `Adapter` with a call like this
`asp, err := b.NewMetricsAspect(env, c.Builder.Params.(adapter.AspectConfig), defs)`

Mixer cache manager caches aspectWrapper. Doing so means that multiple `AspectConfigs` sharing the same `AdapterConfig` will _not_ share the  same object.
