### ISSUE TITLE
Type and Constructors in service config can be hoisted up from the params block.

### ISSUE THREAD

**Issue by guptasu** [istio/mixer#803]
In the new service configs that has Type and Constructor, consider layering each template specific data flat inside the types array as oppose to param or oneof inside a `message Type`

```yaml
types:
  quota:
  - name: ..
    dimensions: ..
    max_amount: ..
  - name: ..
    dimensions: ..
    max_amount: ..
  metric:
  - name:..
```
Same for Constructors

```yaml
types:
  quota:
  - name: ..
    dimensions: ..
    max_amount: ..
  - name: ..
    dimensions: ..
    max_amount: ..
  metric:
  - name:..
```

This is proposed by @louiscryan in one of the PR. To me this is reading better. Once we have the end to end thing working with the agreed upon plan, we can revisit this potential structuring of config. Note this will not affect adapters implementation with Types and Instances, so fixing this is just fixing the codegen and service config yaml files.

**Comment by guptasu** [comment]
# #798

**Comment by ZackButcher** [comment]
FWIW I'm not sure how achievable it is in practice: we might have to generate our config proto as part of mixer assembly, since the templates themselves define the categories we want to group by. Generating that proto makes our config server and related tools more complicated too. Worst case you'd have to build special versions of each of those that match your Mixer; that seems awful to me.

I think using default constructs like we've discussed is a happy middle ground:
```yaml
types:
  - name: Foo
    value: INT64
    dimensions:
      bar: STRING
    constructor:
      value: "source.foo"
      dimensions:
        bar: "target.bar"
  - name: Baz
    dimensions:
      foobar: DURATION
    maxAmount: 7
    constructor:
      value: "target.service"
      dimensions:
        foobar: "target.latency"
```

No, the types aren't separated by their template name, but by convention you can group them together. Also notice here there's no `name` field on the default constructors: they can implicitly take the name of the `Type` they're embedded in. There's no technical reason types and constructors can't share names.
