### ISSUE TITLE
Create a generic batching mechanism for Adapters

### ISSUE THREAD

**Issue by ZackButcher** [istio/mixer#849]
Batching is a common requirement among many adapters. The Mixer should provide tools to make it easy for adapter authors to implement batching. So far we've been careful to design the interfaces exposed to adapters to make them amenable to batching, it's likely we can implement batching in a way transparent to adapters.

**Comment by douglas-reid** [comment]
I think the implementation will be the easy part. The tricky part may be getting the right the config story. 

For instance, should we have something like:

```yaml
handlers:
- name: batchedMetrics
  adapter: batcher
  params:
    handler: myMetrics
    period: 1s
    maxSize: 100MB
- name: myMetrics
  adapter: statsd
  params:
    ipAddr: 10.10.10.10:2343

actions:
- handler: batchedMetrics
  instances:
  - request_count
  - request_duration

```
